# This is a basic workflow to help you get started with Actions

name: My Auto Deployed App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        version: 12

    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install
      
    - name: Creating build
      run: yarn build 

    - name: Installing Surge
      run: npm install -g surge
      
    - name: Deploying on surge
      run: surge ./build http://demoapp00001.surge.sh --token ${{secrets.Surge_token}}
